### ISSUE TITLE
[공지] github 올릴 때 파일 확인

### ISSUE THREAD

**Issue by jeeHwon** [jeeHwon/projectKY#10]
깃 허브 올리실 때 지금 올리는 것처럼 폴더에 넣지말고 파일만 쏴주세요
그럼 1차적으로 DB 폴더와 Front폴더로 제가 분류 작업하겠습니다.
최종적으로 팀장님이 Stampers 폴더로 merge 해주시면 충돌 문제 없을 것 같습니다.

한줄요약 : 폴더에 넣지말자

확인하시면 확인하셨다고 댓글 남겨주세요
우리팀원 댓글 다 달면 제가 issue close 하겠습니다

**Comment by chj9612** [comment]
네 알겠습니다~

**Comment by sarte3** [comment]
확인~

**Comment by JaeKeun1** [comment]
넹 확인했슴니다

**Comment by bee1st** [comment]
확인했습니당

**Comment by zosand123** [comment]
확인했슴다#
