### ISSUE TITLE
[Front] 방만들기 폼 완성 및 DB 연결 후 방불러오기 기능 구현

### ISSUE THREAD

**Issue by jeeHwon** [jeeHwon/projectKY#13]
- 방만들기 폼 완성 => DB연결
- 전체 방 카테고리 화면 완성 => 검색창 및 필터 통해 DB에 있는 방 불러오기 기능 구현

**Comment by bee1st** [comment]
저희 설계 보시고 추가할 목록이나 테이블 있으시면 말씀해주세요

**Comment by jeeHwon** [comment]
DB 연결은 확인했고 컬럼 및 데이터타입 수정 요청 이슈로 올리겠습니다!~
