### ISSUE TITLE
헤더 풋터 만드시는 jsp파일에 추가해주세요~

### ISSUE THREAD

**Issue by zosand123** [jeeHwon/projectKY#14]
헤더,풋터파일 따로 만들었습니다.

<%@include file="header.jsp" %>
    각자의 내용
<%@include file="footer.jsp" %>

index.css, header.jsp, footer.jsp 가져가셔서
jsp파일 만드실때 위처럼 추가해주시면 됩니다. index2.jsp 참고해주세요.

index.css는 flex-wrap을 추가해서 축소시에도 아이템들이 보이게 수정했습니다.
f2의 nav2가 확대, 축소시 따로 노는 현상을 고치려고 어제 거의 밤샜는데 방법을 아직 못 찾았습니다. 
flexbox에서 justify-content : flex-end를 주면 컨테이너와 상관없이 계속 끝에 고정 돼 있는 것 같습니다.
방법을 더 찾아봐야 할 것 같습니다.
일단 헤더풋터 따로 만들었고 만드신 파일들에 index2.jsp처럼 include해주면 됩니다.

혹시 이슈 올릴때 제가 커밋한 파일을 표시하는 방법이 혹시 따로있을까요?

**Comment by jeeHwon** [comment]
고생하셨습니다~!
https://github.com/jeeHwon/projectKY/commit/602e45dfda772a4ce819c43a14f47dd7df0a3c04
일단 링크 올리는 방법이 있겠고 다른 방법도 한번 찾아보고 알려드리겠습니다 ~!

**Comment by jeeHwon** [comment]
헤더 푸터 각 페이지에 추가 완료
