### ISSUE TITLE
본인 작업 파일의 경로 정규화 요청

### ISSUE THREAD

**Issue by jeeHwon** [jeeHwon/projectKY#22]
GitHub에 있는
StampUs2 > WebContent 폴더 내에 본인이 작업하고 있는 파일들을 묶어
폴더로 만드신 후 그 폴더 이름을 댓글로 달아주세요.
폴더명과 작성 파일 현황을 깃 위키에 업데이트 하겠습니다.

https://github.com/jeeHwon/projectKY/wiki/%EA%B7%9C%EC%B9%99_%EB%84%A4%EC%9D%B4%EB%B0%8D(%EC%9E%90%EB%B0%94)

**Comment by jeeHwon** [comment]
전 room 입니다

**Comment by zosand123** [comment]
폴더명 : event
구현내용 : 이벤트게시판+ 댓글

**Comment by JaeKeun1** [comment]
폴더명 : review
구현내용 : 후기게시판, 댓글

**Comment by sarte3** [comment]
폴더명 study_my
구현내용 : 인증방 게시물, 댓글

**Comment by yoo94** [comment]
폴더명 customer
구현내용:공지사항,협력업체(예약),FAQ게시물

**Comment by bee1st** [comment]
폴더명 fboard
구현내용: 자유게시판, 댓글, 검색,

**Comment by jeeHwon** [comment]
finished
